### ISSUE TITLE
Code for [ECCV] Mixed-Precision Neural Network Quantization via Learned Layer-Wise Importance.

### ISSUE THREAD

**Issue by 1hunters** [htqin/awesome-model-quantization#36]
Hi, 

Thanks for this thorough repository. The code for paper [[ECCV](https://arxiv.org/abs/2203.08368)] Mixed-Precision Neural Network Quantization via Learned Layer-Wise Importance is released on:
https://github.com/1hunters/LIMPQ

Best,
Chen

**Comment by htqin** [comment]
Thanks so much!
