### ISSUE TITLE
BinaryViT: Pushing Binary Vision Transformers Towards Convolutional Models

### ISSUE THREAD

**Issue by Phuoc-Hoan-Le** [htqin/awesome-model-quantization#47]
Hi,

Thank you for maintaining this repo. The paper below may be of interest to you. 

BinaryViT: Pushing Binary Vision Transformers Towards Convolutional Models
- [[CVPRW](https://arxiv.org/abs/2306.16678)] BinaryViT: Pushing Binary Vision Transformers Towards Convolutional Models. [**`bnn`**] [[code](https://github.com/phuoc-hoan-le/binaryvit)]

**Comment by Phuoc-Hoan-Le** [comment]
In this work, we found that ViTs suffer a larger performance drop when directly applying convolutional neural network (CNN) binarization methods or existing binarization methods to binarize ViTs compared to CNNs on datasets with a large number of classes such as ImageNet-1k. With extensive analysis, we find that binary vanilla ViTs such as DeiT miss out on a lot of key architectural properties that CNNs have that allow binary CNNs to have much higher representational capability than binary vanilla ViT. Therefore, inspired by the CNN architecture, we include operations from the CNN architecture into a pure ViT architecture to enrich the representational capability of a binary ViT without introducing convolutions. And we explore the effect of architectural operations/properties mainly from CNNs on the classification accuracy of binary Vision Transformers with binary weights and activations, such as using global-average-pooling instead of a cls-token-pooling layer, using a res-post-norm config vs pre-norm config, pyramid-structure vs uniform structure, etc.

Throughout this work, as we are including operations from the CNN architecture into a pure binary ViT architecture, we try to keep the number of parameters/operations the same and also we try to keep it a pure transformer.

**Comment by htqin** [comment]
Thank you!
