### ISSUE TITLE
NeurIPS 2022 paper

### ISSUE THREAD

**Issue by Phuoc-Hoan-Le** [htqin/awesome-model-quantization#49]
Hi,

Thank you for maintaining this repo. The paper below may be of interest to you. 

BiMLP: Compact Binary Architectures for Vision Multi-Layer Perceptrons
- [[NeurIPS](https://proceedings.neurips.cc/paper_files/paper/2022/hash/20f94998511f25bb6378cae0e098bc46-Abstract-Conference.html)] BiMLP: Compact Binary Architectures for Vision Multi-Layer Perceptrons. [**`bnn`**] [[code](https://gitee.com/mindspore/models/tree/master/research/cv/BiMLP)]

**Comment by yifu-ding** [comment]
Thank you for the help! It has been added to the list :)
