### ISSUE TITLE
Workshop vs Conference Papers

### ISSUE THREAD

**Issue by amirgholami** [htqin/awesome-model-quantization#7]
Dear Admins,

First, thanks so much for creating this very useful repository. As a suggestion, I was wondering if it makes sense to differentiate between papers accepted in the main conference vs workshop papers? I believe the current tagging does not differentiate between the two.

Best Regards,
-Amir

**Comment by htqin** [comment]
Thanks for your attention and pointing out. We believe it is meaningful to differentiate between the main conference and workshop papers. And at present, most of the papers in this project are main conference papers. We will improve the project continuously (including the tagging).
