### ISSUE TITLE
adding paper of CVPR2021

### ISSUE THREAD

**Issue by viperit** [htqin/awesome-model-quantization#8]
Dear author!
There are some related papers of CVPR2021.
I copy this from https://github.com/52CV/CVPR-2021-Papers#19

![image](https://user-images.githubusercontent.com/28667932/117594008-cd5f6780-b16f-11eb-8274-24bd3208b902.png)

**Comment by viperit** [comment]
ECCV2020，PAMS: Quantized Super-Resolution via Parameterized Max Scale

**Comment by htqin** [comment]
Thanks! Added.
